#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
require 'arxutils'
require 'everythingop/everythingop'
require 'pathname'

dbconfig = Arxutils::Dbutil::DBCONFIG_MYSQL
dbconfig = Arxutils::Dbutil::DBCONFIG_SQLITE3

hs = {
  "db_dir" => Arxutils::Dbutil::DB_DIR,
  "migrate_dir" => Arxutils::Dbutil::MIGRATE_DIR,
  "config_dir" => Arxutils::Dbutil::CONFIG_DIR,
  "dbconfig" => dbconfig,
  "log_fname" => Arxutils::Dbutil::DATABASELOG,
}



def pathname_test(pa)
  pa_escaped = pa
  pn = Pathname(pa_escaped)
  p pn
  p pn.to_s
  puts pn.expand_path
  puts pn.exist?
  puts pn.mtime
  puts pn.file?
end

fname = ARGV[0]
mode = ARGV[1].to_sym
#fname = nil
eto = Everythingop::Everythingop.new( :db, hs, fname )

eto.set_mode( mode )
eto.reset_hieritem_in_repo

# puts mode
case  mode
when :MIXED_MODE
when :TRACE_MODE
  puts "== ensure_invalid"
  eto.ensure_invalid
else
# no op
end
